#!/bin/sh
#
# Starts openwebrx script
#
# Author: iMakhonin aka Makigo [24.11.2016]
# Email: work.makhonon@gmail.com
#

DAEMON=openwebrx.py
DAEMON_DIR=/www/source-sdr/data/sdr-3
DAEMON_NAME=openwebrx

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start() {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    if [ -x $DAEMON ]; then
        log_action_msg "$DAEMON_NAME binary missing - not starting"
        log_end_msg 1
    fi

    if start-stop-daemon --start --background --chuid $DAEMON_USER --chdir $DAEMON_DIR --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS; then
        log_end_msg 0
    fi
}
do_stop() {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    killall -9 csdr rtl_sdr
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: service $DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
